name: Trigger Frontend Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cron repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-shared-role
          aws-region: eu-west-1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod tidy && go mod download

      - name: Build
        run: go build -v ./...

      - name: Generate output.json
        run: |
          go run main.go || { echo "Error: Failed to generate output.json"; exit 1; }

      - name: Verify output.json
        run: |
          ls -l output.json
          cat output.json

      - name: Upload output.json to our shared bucket
        run: |
          aws s3 cp output.json s3://${{ secrets.SHARED_BUCKET }}/cron-content-generator/output.json

      - name: Trigger Workflow to deploy frontend
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/uglyorganization/frontend/dispatches \
          -d '{"event_type": "trigger-deploy"}' 
