name: Trigger Frontend Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow to deploy frontend-dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/uglyorganization/frontend-dev/dispatches \
          -d '{"event_type": "trigger-deploy"}' 
