name: Trigger Frontend Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cron repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Generate output.json
        run: |
          go run main.go || { echo "Error: Failed to generate output.json"; exit 1; }

      - name: Verify output.json
        run: |
          ls -l output.json
          cat output.json

      - name: Encode output.json and set as environment variable
        run: echo "JSON_PAYLOAD_BASE64=$(cat output.json | base64)" >> $GITHUB_ENV
        shell: bash

      - name: Trigger frontend workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: uglyorganization/frontend
          event-type: trigger-deploy
          client-payload: '{"payload": "${{ fromBase64(env.JSON_PAYLOAD_BASE64) }}"}'
