name: Trigger Frontend Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cron repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod tidy && go mod download

      - name: Build
        run: go build -v ./...

      - name: Generate output.json
        run: |
          go run main.go || { echo "Error: Failed to generate output.json"; exit 1; }

      - name: Verify output.json
        run: |
          ls -l output.json
          cat output.json

      - name: Read JSON content and set output
        id: read-json
        run: |
          payload=$(jq -c . output.json)
          echo "::set-output name=json_content::$payload"

      - name: Trigger frontend workflow via curl
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Using payload: ${{ steps.read-json.outputs.json_content }}"
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            --fail \
            https://api.github.com/repos/uglyorganization/frontend/dispatches \
            -d "{\"event_type\": \"trigger-deploy\", \"client_payload\": ${{ steps.read-json.outputs.json_content }}"
        shell: bash
