name: Trigger Frontend Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cron repository
        uses: actions/checkout@v4

      - name: Read output.json
        id: read-json
        run: |
          ls -l  # List files in the current directory for debugging
          if [ -f "output.json" ]; then
            echo "File exists, reading contents..."
            echo "::set-output name=json::$(cat output.json)"
          else
            echo "Error: output.json file not found"
            exit 1
          fi

      - name: Trigger frontend workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: uglyorganization/frontend
          event-type: trigger-deploy
          client-payload: ${{ steps.read-json.outputs.json }}
