name: Trigger Target Workflow

on:
  workflow_dispatch:


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Run  main to generate the `output.json`
        run: go run main.go
      - name: Run cURL command to trigger
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -d "{\"event_type\": \"${{ env.event_type }}\", \"json\": $(cat output.json)}" \
            https://api.github.com/repos/${{ env.repo_owner }}/${{ env.repo_name }}/dispatches
        env:
          event_type: "trigger-deploy"
          repo_owner: ${{ github.repository_owner }}
          repo_name: "frontend"
