name: Trigger Frontend Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cron repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Generate output.json
        run: |
          go run main.go || { echo "Error: Failed to generate output.json"; exit 1; }

      - name: Verify output.json
        run: |
          ls -l output.json
          cat output.json

      - name: Read JSON content and set output
        id: read-json
        run: |
          json_content=$(jq -c . < output.json)
          echo "::set-output name=json_content::$json_content"

      - name: Trigger frontend workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: uglyorganization/frontend
          event-type: trigger-deploy
          client-payload: ${{ steps.read-json.outputs.json_content }}